# Generated by Django 6.1.1 on 2026-09-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0018_add_homepage_banner_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("new_cycle", "New Reporting Cycle"),
                        ],
                        help_text="The type of correspondence that was sent",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The email subject line", max_length=255
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The sanitised HTML body sent when a single message was used for all groups",
                    ),
                ),
                (
                    "group_messages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-group sanitised HTML messages when per-group messaging was used. Keys: ba_leads, project_leads, team_members",
                    ),
                ),
                (
                    "recipient_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Groups selected for this send, e.g. ['ba_leads', 'project_leads']",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Resolved recipients captured at send time. Each entry: {'pk': int, 'name': str, 'email': str, 'group': str}",
                    ),
                ),
                (
                    "emails_sent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of recipients that successfully received the email",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who initiated the send",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_email_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Record",
                "verbose_name_plural": "Email Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="adminoption_kind_fd0614_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="adminoption_created_dd6726_idx"
                    ),
                ],
            },
        ),
    ]
