# Generated by Django 6.1.1 on 2026-09-14 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0019_emailrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailrecord",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="True when the send occurred while email testing mode was active, meaning delivery was redirected to the test user rather than the resolved recipients. Used to distinguish test sends from official ones.",
            ),
        ),
        migrations.AddIndex(
            model_name="emailrecord",
            index=models.Index(
                fields=["is_test", "-created_at"], name="adminoption_is_test_4069fa_idx"
            ),
        ),
    ]
