# Generated by Django 6.1.1 on 2026-09-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_annualreport_pdf_generation_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEditException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="The moment after which this exception no longer grants edit access."
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_exceptions",
                        to="documents.projectdocument",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrator who granted or last extended this exception.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edit_exceptions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user granted temporary edit access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_edit_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Edit Exception",
                "verbose_name_plural": "Document Edit Exceptions",
                "indexes": [
                    models.Index(
                        fields=["document", "user"],
                        name="documents_d_documen_1e6c11_idx",
                    )
                ],
            },
        ),
    ]
